spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    username: root
    password: mysql1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop   ## create-drop --- create table at start, and drop when server stops.. comment this in production


## Add below property to use InnoDB engine instead of MyISAM engine
##   spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
